### ISSUE TITLE
Connection to robot 

### ISSUE THREAD

**Issue by pouyan-asg** [Mecademic/mecademicpy#10] opened 2023-03-08 15:50 UTC
Hi, 
For connection to Meca500 through ethernet cable I use following code:

`robot.Connect(address='192.168.0.100', disconnect_on_exception=False, enable_synchronous_mode=False)`

But when I stop the running code, it is impossible to run again. I should activate the robot by Webpage and deactivate again to Run the code. In summary, back to back connection is impossible. 

Is there any way to handle it? 

Thank you very much for your time and consideration

**Comment by gbmecademic** [comment] 2023-03-08 15:59
Hello,
I would need more details on your code to understand your issue. When I try it on my side I can connect after exiting the script.

Does your script output any error?
When connecting to the web interface, is the robot in an error state?

Also keep in mind that if the connection to the robot is cut while the robot is performing a command like a movement, it will pause the robot and you need to do a ResumeMotion for the robot to keep moving. If after exiting the script you open the web interface, is the pause button red?

Thank you,

**Comment by pouyan-asg** [comment] 2023-03-08 16:53
Hi @gbmecademic ,

Thanks for your reply.

About your questions:

- Does your script output any error? No, I just stop the code running manually 

- When connecting to the web interface, is the robot in an error state? No, everything is good and there is not any out of range or singularity errors.

- Also keep in mind that if the connection to the robot is cut while the robot is performing a command like a movement, it will pause the robot and you need to do a ResumeMotion for the robot to keep moving. If after exiting the script you open the web interface, is the pause button red? right now, I added ResumeMotion at the top of my code and it works. When I stop the code, then I can continue without needing to activate/deactivate from Webpage.

If I should do anything else, please let me know.

Thank you very much

**Comment by gbmecademic** [comment] 2023-03-08 17:00
Adding a resume motion at the start is a good practice especially if you do not do a manual disconnect from the script. You are using the option 

disconnect_on_exception=False

and this measn that if you stop the script manually (by doing ctrl+C for instance) the robot will think that the connection was accidentally dropped and will pause the motion. It is a good practice to use the

robo.Disconnect()

method before exiting the script to avoid this or use
disconnect_on_exception=True

Let me know if I can close this issue or if you have other questions.

**Comment by pouyan-asg** [comment] 2023-03-09 14:40
Thanks @gbmecademic for your guidance. 

I used ResumeMotion to continue from last movement when I stop the code deliberately. it worked but in some cases shows a message that needs external check point. I used SetCheckpoint(n) but it did not work. Do you have any idea how can I resume motion after stopping manually? 

My first question relates to this too. When I stop the code manually (through IDE), I need to connect once through webpage and then again connect through code. If there is a way to resume last motion and make connection without requirement to connect through webpage that would be perfect.

**Comment by gbmecademic** [comment] 2023-03-09 15:15
Hello,
I was able to reproduce the chekcpoint message. This happens when you use a wait function and the program crashes somewhere else. When using a wait function, the API will use a SetCheckpoint to know when the bloc of commands is done. If the program crashes before the checkpoint is sent back, when you start again the robot will finish its movement and will send that checkpoint. The API was not expecting a checkpoint because it restarted so it gives you a warning message. It doesn't really cause any issues unless you use ExpectExternalCheckpoint() command for a different checkpoint.

I am not sure why you would need to connect to the web interface before running the code. The web interface is really only a javascript program that does the same thing as our API so it doesn't really do anything special. There is no requirement to connect to the web page before, you should be able to restart your code and if you are using the ResumeMotion command if there are still commands in the robot's motion queue, it should start moving again.

I tested it on my robot and computer and it works fine. I would recommend not stopping the robot and restarting it like that as it is not really a good practice anyways. You can use the PauseMotion and stay in your program if you plan on restarting it. This will prevent some checkpoint issues or connection issues.

**Comment by pouyan-asg** [comment] 2023-03-10 02:30
Thanks @gbmecademic,

For my code, I used  robot.WaitIdle() and as I found it causes the error of checkpoint whenever I resume the motion. About the second part, I agree and it is wondering why I can not connect again. Regarding your suggestion, I should send PauseMotion (via webpage or shell) during robot working to stop it and then I can resume when run again. If I wrong please correct me.

Finally, with this way, I can not completely stop a code and run again (I only can pause robot motion and resume it).

regards,

**Comment by gbmecademic** [comment] 2023-03-10 20:23
Hello,
You can send a message from the current script that you are running but you can only have one connection active at a time on the robot so you will not be able to connect using the web interface at the same time as the Python script.

When you say that you cannot connect again, what do you mean? Is it that there is nothing happening or do you get an error message?

**Comment by pouyan-asg** [comment] 2023-03-13 16:22
Hello again,

I think my explanation was not clear. I know that it is impossible to connect at same time via Webpage and IDE. 
Consider I want to send some predefined trajectories to robot that is written in Python. I can connect to robot through VS Code (after deactivation from Webpage) and everything works well. When I stop the code, I can not connect through the code again. it does not show any error but I need to connect via Webpage then disconnect and then Run code. 

I just could not find the reason why I am not able to make connection through code back to back and between each stop I need to connect by Webpage.

Thank you in advance

**Comment by gbmecademic** [comment] 2023-03-14 14:55
Hello,
I am not able tor eproduce your error. This might be reltaed to how you kill the process and maybe the socket doesn't close properly and is reset when you connect through the web interface.

Could you try to run your script in a separate terminal instead of using VS Code? There's might be some issues with the VSCode debugger that causes this problem.

If this still does not work you can try to run a wireshark capture while trying to connect to the robot. Then send us the capture and the robot's logs and we might be able to find the issue.

**Comment by pouyan-asg** [comment] 2023-03-17 18:06
Thanks Gabriel for your helps.

**Closed as completed** 2023-03-17 18:06 UTC
